import = ["~/.config/alacritty/dracula.toml"]

[window]
startup_mode = "Maximized"
opacity = 0.90
padding = { x = 0, y = 0 }
dynamic_padding = true


[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Medium Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "ExtraBold Italic" }
offset = { x = 0, y = -1 }
size = 10.5
