"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch\
$git_status\
$custom\
$fill\
$aws\
$nodejs\
$python\
$package\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

# Use the color palette
palette = "dracula"

[directory]
style = 'bold fg:cyan'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:purple'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'


[git_status]
style = "bold purple" # Base color for the status block
format = '([\[$all_status$ahead_behind\]]($style) )'

# Colorize specific status indicators
conflicted = "[═$count](bold red)"
ahead = "[⇡$count](bold green)"
behind = "[⇣$count](bold red)"
#chroot = "[chroot](bold white)"
diverged = "[⇕⇡$ahead_count⇣$behind_count](bold yellow)"
#up_to_date = "[✓](bold green)"
untracked = "[?$count](bold blue)"
stashed = "[ $count](bold dark_gray)"
modified = "[!$count](bold yellow)"
staged = "[+$count](bold green)"
renamed = "[»$count](bold cyan)"
deleted = "[✘$count](bold red)"

# [custom.git_clean]
# command = "git diff --quiet && git diff --cached --quiet && test -z \"$(git status --porcelain)\" && git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1 && test -z \"$(git rev-list --count HEAD..@{u})\" && test -z \"$(git rev-list --count @{u}..HEAD)\""
# when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
# require_repo = true
# symbol = "✓"
# style = "bold green"
# format = "[✓]($style) "


[custom.git_clean]
command = 'test -z "$(git status | grep -ie changes)" && echo "✓"'
when = 'git rev-parse --is-inside-work-tree 2>/dev/null'
require_repo = true
style = "bold green"
format = "[$output]($style) "


[fill]
symbol = ' '

[python]
style = 'yellow bold'
symbol = ' '
format = '[${symbol}${pyenv_prefix} ($version) (\($virtualenv\) )]($style)'
pyenv_version_name = true  # need to install pyenv
pyenv_prefix = ''
detect_env_vars = [ "PATH" ]


[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[golang]
style = 'blue'
symbol = ' '

[haskell]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[ruby]
style = 'blue'
symbol = ' '

[package]
symbol = '󰏗 '

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[os]
style = "cyan"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""


# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

